### PR TITLE
Allow checking if gravatar exists

### PR DESCRIPTION
**Pull request by AO16**
Trying to think of the best way to do this. But in general my idea would be to keep the inline component as-is and then add an additional block component that yields `image` and `exists`.

Would look something like this:

```
{{#gravatar-image email='test@github.com' as |g|}}
  {{#if g.exists}}
    {{g.image}}
  {{else}}
    Image not found!
  {{/if}}
{{/gravatar-image}}
```

### CODE REVIEW

**Comment by AO16** [comment]
I ended up adding a new component `has-gravatar` that leaves that original component alone and just does a check with a yield.

**Comment by AO16** [comment]
If you think this is something that looks good, I can take the time to write tests and everything for it.

**Comment by AO16** [comment]
@johnotander I moved the ajax call into a service and ran some unit tests over it. Since components aren't very good with async, I wasn't able to do integration tests. Let me know if you need anything else.

Thanks!

**Comment by johnotander** [comment]
Radical! Thanks!

**Comment by rafalt-iRonin** [comment]
I'm attaching small Pull Request. Please have a look. I tested with our app, worked flawlessly.

https://github.com/johnotander/ember-cli-gravatar/pull/55

**Pull request merged**
