### PR TITLE
Making Updates to the Rendered DOM

### PR DESCRIPTION
**Pull request by rafalt-iRonin**
Hi Guys, 

Nice addon by the way :)

I have observed that has-gravatar checking doesn't work on DOM updates, here is a fix.

What do you think?

Best,
Rafał

### CODE REVIEW

**Comment by johnotander** [comment]
Hey @rafalt-iRonin. This looks great, thanks! 🙇 ✨I should have time this evening to give it a quick test as well and then deploy a new version if all goes well. When that happens I'll let you know.

**Comment by rafalt-iRonin** [comment]
Hi @johnotander 

Thanks for looking at this! If I can help with fixing CI, let me know. Locally tests was green.

**Comment by johnotander** [comment]
Looks like the node version is out of date, so no worries I'll get CI passing. Thanks again for your contribution!

**Comment by johnotander** [comment]
Published to npm as `ember-cli-gravatar@3.8.1`. Thanks again and my apologies on the delay.

**Pull request merged**
